services:
  backend:
    build: ./backend
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=development
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm start
